import localFont from "next/font/local";
import "./globals.css";
import Headers from "./Components/Headers";
import Sidebar from "./Components/Sidebar";
import Intensity from "./AdminComponents/Intensity";
import Year from "./AdminComponents/Year";
import Region from "./AdminComponents/Region";
import City from "./AdminComponents/City";
import { Likelihood } from "./AdminComponents/Likelihood";
import Topics from "./AdminComponents/Topics";
import Relevance from "./AdminComponents/Relevance";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Headers/>
        <Sidebar/>
        
        <Intensity/>
        <Relevance/>
        <City/>
        <Topics/>
        <Region/>
        <Likelihood/>
        <Year/>


        {children}
      </body>
    </html>
  );
}
